# Railway Nixpacks configuration
[phases.setup]
nixPkgs = ["...", "php82", "php82Packages.composer", "nodejs-18_x"]

[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-dev",
    "npm ci",
    "npm run build"
]

[phases.build]
cmds = [
    # Make start script executable
    "chmod +x start.sh"
]

[start]
cmd = "./start.sh"
