# Railway Nixpacks configuration
[phases.setup]
nixPkgs = ["...", "php82", "php82Packages.composer", "nodejs-18_x"]

[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-dev --no-interaction",
    "npm ci",
    "npm run build"
]

[phases.build]
cmds = [
    # Copy environment file for build phase (without database operations)
    "cp .env.example .env",
    "php artisan key:generate --force",
    # Don't cache config during build - will be done at runtime with proper env vars
    "echo 'Skipping config cache during build - will cache at runtime'"
]

[start]
cmd = "bash start.sh"
